"""add_show_image_info_to_playlists

Revision ID: 2cfb3ac760a2
Revises: ce5826f818f3
Create Date: 2025-10-31 09:57:49.635975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2cfb3ac760a2'
down_revision: Union[str, Sequence[str], None] = 'ce5826f818f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if column already exists (it's in initial schema)
    connection = op.get_bind()
    result = connection.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'playlists' AND column_name = 'show_image_info'"
    ))
    column_exists = result.scalar() > 0
    
    if not column_exists:
        op.add_column('playlists', sa.Column('show_image_info', sa.Boolean(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'show_image_info')
    # ### end Alembic commands ###
