"""Add playlist variants for resolution-specific playlists

Revision ID: ce5826f818f3
Revises: d2ccc3099d51
Create Date: 2025-10-28 19:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ce5826f818f3'
down_revision: Union[str, None] = 'd2ccc3099d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('variant_type', sa.Enum('original', '2k_portrait', '4k_portrait', '2k_landscape', '4k_landscape', 'custom', name='playlistvarianttype'), nullable=False),
    sa.Column('target_width', sa.Integer(), nullable=True),
    sa.Column('target_height', sa.Integer(), nullable=True),
    sa.Column('optimized_sequence', sa.JSON(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('min_width', sa.Integer(), nullable=True),
    sa.Column('max_width', sa.Integer(), nullable=True),
    sa.Column('min_height', sa.Integer(), nullable=True),
    sa.Column('max_height', sa.Integer(), nullable=True),
    sa.Column('preferred_orientation', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_variants_id'), 'playlist_variants', ['id'], unique=False)
    op.create_index(op.f('ix_playlist_variants_playlist_id'), 'playlist_variants', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_variants_variant_type'), 'playlist_variants', ['variant_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_variants_variant_type'), table_name='playlist_variants')
    op.drop_index(op.f('ix_playlist_variants_playlist_id'), table_name='playlist_variants')
    op.drop_index(op.f('ix_playlist_variants_id'), table_name='playlist_variants')
    op.drop_table('playlist_variants')
    # ### end Alembic commands ###

