"""Add resolution fields to display devices

Revision ID: d2ccc3099d51
Revises: 5595cc4b4e79
Create Date: 2025-10-28 16:10:36.068574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ccc3099d51'
down_revision: Union[str, Sequence[str], None] = '5595cc4b4e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns already exist (they're in initial schema now)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('display_devices')]
    
    if 'screen_width' not in columns:
        op.add_column('display_devices', sa.Column('screen_width', sa.Integer(), nullable=True))
    if 'screen_height' not in columns:
        op.add_column('display_devices', sa.Column('screen_height', sa.Integer(), nullable=True))
    if 'device_pixel_ratio' not in columns:
        op.add_column('display_devices', sa.Column('device_pixel_ratio', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('display_devices', 'device_pixel_ratio')
    op.drop_column('display_devices', 'screen_height')
    op.drop_column('display_devices', 'screen_width')
    # ### end Alembic commands ###
